import type { IntentLanding } from './intentLandings';

// Per-model Hyundai landings. Russian rewritten natively (russian-copy skill), em-dashes stripped.
export const MODEL_LANDINGS: IntentLanding[] = [
  {
    slug: "hyundai-elantra",
    filters: "make=Hyundai&model=Elantra&sort=hunterScore",
    related: ["hyundai-sonata", "hyundai-tucson", "hyundai-santa-fe"],
    en: {
      title: "Hyundai Elantra Lease Deals in SoCal | Hunter Lease",
      description: "Lease a Hyundai Elantra in Southern California with the all-in price, money factor, and drive-off shown up front. No markups. See your Hunter Score.",
      keywords: "Hyundai Elantra lease, Hyundai Elantra lease Los Angeles, Elantra lease deals California, compact sedan lease SoCal, lease calculator Los Angeles, transparent car lease California, first car lease Los Angeles",
      h1: "Lease a Hyundai Elantra in Southern California",
      intro: "The Elantra is a sharp, fuel-sipping compact sedan that handles the LA commute and is easy to step into for a first US car. Browse our Elantra listings with the full number in plain sight, then take it from there.",
      bullets: ["Built for the value commuter and the first-time US buyer: low running costs, easy parking, and a clean entry point into your own lease.", "One all-in price, with the money factor and drive-off broken out in the open. No dealer markup on the rate, no junk add-ons.", "Every Elantra carries a Hunter Score so you can see how the deal stacks up before you commit. An SSN is required; thin or new US credit is fine, we match you with lenders friendly to first-time borrowers and a co-signer can help."],
      cta: "See Elantra listings and your Hunter Score",
    },
    ru: {
      title: "Лизинг Hyundai Elantra в Калифорнии | Hunter Lease",
      description: "Лизинг Hyundai Elantra в Южной Калифорнии. Полная цена, money factor и платёж при выдаче на виду. Без наценок. Смотрите Hunter Score.",
      keywords: "Hyundai Elantra lease, Hyundai Elantra lease Los Angeles, Elantra lease deals California, compact sedan lease SoCal, lease calculator Los Angeles, transparent car lease California, first car lease Los Angeles",
      h1: "Лизинг Hyundai Elantra в Южной Калифорнии",
      intro: "Elantra это компактный седан: мало ест, легко паркуется, спокойно тянет дорогу по LA. Хороший первый лизинг в США. Смотрите предложения по Elantra, где вся цифра на виду, и решайте сами.",
      bullets: ["Для тех, кто считает расходы, и для первой машины в США: дешёвое владение, лёгкая парковка, понятный вход в лизинг.", "Одна цена, всё включено. Money factor и платёж при выдаче разложены открыто. Без дилерской наценки на ставку и без лишних допов.", "У каждой Elantra есть Hunter Score, чтобы вы видели силу сделки до решения. SSN нужен обязательно. Короткая кредитная история в США это нормально: подбираем банки, которые дают первый кредит, а co-signer помогает."],
      cta: "Смотреть Elantra и свой Hunter Score",
    },
  },
  {
    slug: "hyundai-sonata",
    filters: "make=Hyundai&model=Sonata&sort=hunterScore",
    related: ["hyundai-tucson", "hyundai-santa-fe", "hyundai-palisade"],
    en: {
      title: "Lease a Hyundai Sonata in SoCal | Hunter Lease",
      description: "Lease the Hyundai Sonata in Southern California with all-in pricing, the money factor and drive-off shown, a Hunter Score, and zero dealer markups.",
      keywords: "Hyundai Sonata lease, lease Hyundai Sonata Los Angeles, Hyundai Sonata lease deals California, midsize sedan lease SoCal, Sonata lease specials Los Angeles, family sedan lease California",
      h1: "Hyundai Sonata Lease, Priced in the Open",
      intro: "The Sonata is a roomy midsize sedan built for the long SoCal commute and family weekends. We put every number on the table so you hold the leverage at the dealership.",
      bullets: ["Built for commuters and families who want space, comfort, and a quiet highway ride without stepping up to a luxury badge.", "All-in price with the money factor and full drive-off shown line by line, so you know exactly what you are signing before you sign it.", "Every deal carries a Hunter Score that grades how strong the terms are, with no dealer markups added on top of the lender's numbers."],
      cta: "See Sonata deals in the catalog",
    },
    ru: {
      title: "Лизинг Hyundai Sonata в Калифорнии | Hunter Lease",
      description: "Лизинг Hyundai Sonata в Южной Калифорнии: полная цена, money factor и платёж при выдаче на виду, Hunter Score и без наценок дилера.",
      keywords: "Hyundai Sonata lease, lease Hyundai Sonata Los Angeles, Hyundai Sonata lease deals California, midsize sedan lease SoCal, Sonata lease specials Los Angeles, family sedan lease California",
      h1: "Лизинг Hyundai Sonata с открытой ценой",
      intro: "Sonata это просторный седан среднего класса: для долгой дороги по Южной Калифорнии и для семьи на выходных. Все цифры на столе, поэтому у дилера сильнее за столом вы.",
      bullets: ["Простор, комфорт и тихая трасса, но без перехода на премиум-марку. Для тех, кто ездит на работу и возит семью.", "Цена со всем включённым. Money factor и платёж при выдаче разобраны по строкам, чтобы вы знали, что подписываете, до подписи.", "У каждой сделки есть Hunter Score: он показывает, насколько сильны условия. Наценку дилера поверх банковской ставки мы не добавляем."],
      cta: "Смотреть Sonata в каталоге",
    },
  },
  {
    slug: "hyundai-tucson",
    filters: "make=Hyundai&model=Tucson&sort=hunterScore",
    related: ["hyundai-santa-fe", "hyundai-palisade", "hyundai-kona"],
    en: {
      title: "Hyundai Tucson Lease in SoCal | Hunter Lease",
      description: "Lease a Hyundai Tucson in Southern California with the all-in price, money factor and drive-off shown up front. SSN required, thin US credit fine.",
      keywords: "Hyundai Tucson lease, Hyundai Tucson lease Los Angeles, Tucson lease deal California, compact SUV lease Southern California, crossover lease LA, Hyundai lease deals SoCal",
      h1: "Lease a Hyundai Tucson in Southern California",
      intro: "The Tucson is the compact crossover most SoCal drivers shortlist first, and we quote it the way a numbers-first buyer wants it: every figure on the table before you commit. You bring an SSN and new or thin US credit; we match you with lenders friendly to first-time borrowers.",
      bullets: ["See the all-in price, money factor, and exact drive-off on every Tucson trim, with no dealer markups added on our side.", "Each quote carries a Hunter Score so you can judge the deal on its own merits instead of trusting a sales pitch.", "Built for drivers with new or thin US credit: an SSN is required, a co-signer can strengthen your terms, and we help you build history."],
      cta: "Browse Hyundai Tucson lease quotes",
    },
    ru: {
      title: "Лизинг Hyundai Tucson в Калифорнии | Hunter Lease",
      description: "Лизинг Hyundai Tucson в Южной Калифорнии: полная цена, money factor и платёж при выдаче видны сразу. Нужен SSN, короткая кредитная история подойдёт.",
      keywords: "Hyundai Tucson lease, Hyundai Tucson lease Los Angeles, Tucson lease deal California, compact SUV lease Southern California, crossover lease LA, Hyundai lease deals SoCal",
      h1: "Лизинг Hyundai Tucson в Южной Калифорнии",
      intro: "Tucson это компактный кроссовер, который в Южной Калифорнии чаще всего ставят в шорт-лист первым. Цифры по нему мы показываем так, как нужно тем, кто считает: все суммы на столе ещё до решения. От вас SSN и хоть совсем короткая кредитная история в США. Банки, которые дают первый кредит, подберём.",
      bullets: ["Полная цена, money factor и точный платёж при выдаче (drive-off) по каждой комплектации Tucson. Наценок сверху от нас нет.", "К каждому расчёту идёт Hunter Score: вы оцениваете сделку по фактам, а не по словам продавца.", "Для водителей с короткой кредитной историей в США: нужен SSN, co-signer улучшит условия, а историю помогаем выстроить."],
      cta: "Смотреть расчёты по Hyundai Tucson",
    },
  },
  {
    slug: "hyundai-santa-fe",
    filters: "make=Hyundai&model=Santa%20Fe&sort=hunterScore",
    related: ["hyundai-palisade", "hyundai-kona", "hyundai-ioniq-5"],
    en: {
      title: "Hyundai Santa Fe Lease Deals in SoCal | Hunter Lease",
      description: "Lease a Hyundai Santa Fe in Southern California with the all-in price, money factor and drive-off shown up front and ranked by Hunter Score. No dealer markups.",
      keywords: "Hyundai Santa Fe lease, Santa Fe lease deals Los Angeles, midsize SUV lease California, family SUV lease Southern California, transparent Santa Fe lease, лизинг Hyundai Santa Fe Калифорния",
      h1: "Hyundai Santa Fe lease deals",
      intro: "The Santa Fe is a midsize SUV built for families who want a third row and real cargo room. Here every Santa Fe deal shows the all-in price, money factor and drive-off up front, ranked by Hunter Score.",
      bullets: ["All-in price, money factor and drive-off shown on every Santa Fe, not revealed at signing", "Ranked by Hunter Score from 0 to 100 so you see how each deal compares before you talk to anyone", "Dealer pricing passed straight through with no markups, lease or finance, an SSN is required and thin US credit is fine"],
      cta: "See Santa Fe lease deals",
    },
    ru: {
      title: "Лизинг Hyundai Santa Fe в Южной Калифорнии | Hunter Lease",
      description: "Лизинг Hyundai Santa Fe в Южной Калифорнии: цена all-in, ставка и платёж при выдаче показаны заранее, ранжировано по Hunter Score. Без наценок дилера.",
      keywords: "Hyundai Santa Fe lease, Santa Fe lease deals Los Angeles, midsize SUV lease California, family SUV lease Southern California, transparent Santa Fe lease, лизинг Hyundai Santa Fe Калифорния",
      h1: "Лизинг Hyundai Santa Fe",
      intro: "Santa Fe это среднеразмерный внедорожник для семьи: третий ряд и реальное место под багаж. По каждой сделке на Santa Fe цена со всем включённым, ставка и платёж при выдаче показаны заранее, а сами сделки ранжированы по Hunter Score.",
      bullets: ["Цена со всем включённым, ставка и платёж при выдаче на виду по каждому Santa Fe. Не открываются при подписании, а видны сразу.", "Ранжируем по Hunter Score от 0 до 100, чтобы сделку на фоне других вы видели ещё до разговора с дилером.", "Цену дилера передаём напрямую, без наценок, хоть лизинг, хоть finance. SSN нужен обязательно, короткая кредитная история в США это нормально."],
      cta: "Смотреть сделки на Santa Fe",
    },
  },
  {
    slug: "hyundai-palisade",
    filters: "make=Hyundai&model=Palisade&sort=hunterScore",
    related: ["hyundai-kona", "hyundai-ioniq-5", "hyundai-ioniq-6"],
    en: {
      title: "Hyundai Palisade Lease in SoCal | Hunter Lease",
      description: "Lease a Hyundai Palisade in Los Angeles and across California with the all-in price, money factor, drive-off, and Hunter Score shown upfront. No dealer markups.",
      keywords: "Hyundai Palisade lease, Palisade lease Los Angeles, Hyundai Palisade lease deals California, 3-row SUV lease SoCal, Palisade lease specials, lease Palisade near me, Southern California Hyundai lease",
      h1: "Lease a Hyundai Palisade",
      intro: "A three-row SUV built for big families and weekend trips, leased on terms you can actually read. Browse Palisade inventory across Southern California with every number on the table.",
      bullets: ["Built for the people who fill all three rows: car seats, teammates, in-laws, and a trunk full of gear, with a cabin that feels a class above the badge.", "We show the all-in price, the money factor, and the full drive-off before you commit, so the lease you see is the lease you sign.", "Every Palisade carries a Hunter Score that grades the deal against the market, and we add no dealer markups on top."],
      cta: "See Palisade lease offers",
    },
    ru: {
      title: "Лизинг Hyundai Palisade в Калифорнии | Hunter Lease",
      description: "Hyundai Palisade в лизинг в Лос-Анджелесе и по Калифорнии: полная цена, money factor, drive-off и Hunter Score сразу видны. Без наценок дилера.",
      keywords: "Hyundai Palisade lease, Palisade lease Los Angeles, Hyundai Palisade lease deals California, 3-row SUV lease SoCal, Palisade lease specials, lease Palisade near me, Southern California Hyundai lease",
      h1: "Hyundai Palisade в лизинг",
      intro: "Трёхрядный внедорожник для большой семьи и поездок на выходные, с условиями, которые реально читаются. Смотрите Palisade по всей Южной Калифорнии, где каждая цифра на виду.",
      bullets: ["Для тех, кто заполняет все три ряда: детские кресла, команда, родня и багажник со снаряжением. Салон тут ощущается на класс выше шильдика.", "Полную цену, money factor и весь платёж при выдаче показываем до согласия. Подписываете ровно тот лизинг, который видите.", "У каждого Palisade есть Hunter Score: он оценивает сделку относительно рынка. Дилерских наценок сверху мы не ставим."],
      cta: "Смотреть предложения по Palisade",
    },
  },
  {
    slug: "hyundai-kona",
    filters: "make=Hyundai&model=Kona&sort=hunterScore",
    related: ["hyundai-ioniq-5", "hyundai-ioniq-6", "hyundai-elantra"],
    en: {
      title: "Hyundai Kona Lease in SoCal | Hunter Lease",
      description: "Lease a Hyundai Kona in Los Angeles and across Southern California with all-in pricing, money factor and drive-off shown, and no dealer markups.",
      keywords: "Hyundai Kona lease, Hyundai Kona lease Los Angeles, Kona lease deals California, subcompact SUV lease SoCal, lease calculator, transparent lease deals California",
      h1: "Lease a Hyundai Kona in Southern California",
      intro: "The Hyundai Kona is a right-sized subcompact SUV for city driving and tight budgets. Browse our Kona lease listings with every number shown up front, the way a deal should look.",
      bullets: ["Built for SoCal city life: an easy-to-park subcompact SUV with room for daily errands, commutes, and weekend trips, a fit for first car buyers and anyone watching the monthly budget.", "See the real deal before you commit: all-in monthly price, the money factor, and the full drive-off are shown on every Kona listing, with no dealer markup added to the lender's rate.", "A Hunter Score ranks each Kona lease against comparable Southern California deals, so you can tell a strong offer from an average one at a glance. New to US credit is fine; an SSN is required, a co-signer can help, and we match you with lenders friendly to first-time borrowers."],
      cta: "See Hyundai Kona lease listings",
    },
    ru: {
      title: "Лизинг Hyundai Kona в Калифорнии | Hunter Lease",
      description: "Лизинг Hyundai Kona в Лос-Анджелесе и по всей Южной Калифорнии: цена со всеми сборами, money factor и платёж при выдаче на виду, без наценок дилера.",
      keywords: "Hyundai Kona lease, Hyundai Kona lease Los Angeles, Kona lease deals California, subcompact SUV lease SoCal, lease calculator, transparent lease deals California",
      h1: "Лизинг Hyundai Kona в Южной Калифорнии",
      intro: "Hyundai Kona это компактный кроссовер как раз под город и спокойный бюджет. Смотрите предложения по лизингу Kona, где все цифры показаны сразу, как и должно быть в честной сделке.",
      bullets: ["Под жизнь в городах Южной Калифорнии: компактный кроссовер, легко парковать, хватает места на дела по будням и вылазки по выходным. Подойдёт под первую машину и тем, кто следит за платежом.", "Настоящую сделку видите до решения: итоговая цена со всем включённым, money factor и полный платёж при выдаче на каждом объявлении Kona. Наценки дилера поверх банковской ставки нет.", "Hunter Score сравнивает каждый лизинг Kona с похожими по Южной Калифорнии, и сильную сделку от средней вы отличаете сразу. Новая кредитная история в США это нормально. SSN нужен обязательно, co-signer помогает, банки под первый кредит подберём."],
      cta: "Смотреть лизинг Hyundai Kona",
    },
  },
  {
    slug: "hyundai-ioniq-5",
    filters: "make=Hyundai&model=Ioniq%205&sort=hunterScore",
    related: ["hyundai-ioniq-6", "hyundai-elantra", "hyundai-sonata"],
    en: {
      title: "Hyundai Ioniq 5 Lease in Southern California | Hunter Lease",
      description: "Lease a Hyundai Ioniq 5 EV across Southern California with an all-in price, money factor, and drive-off shown up front. No dealer markups.",
      keywords: "Hyundai Ioniq 5 lease, Ioniq 5 lease Los Angeles, Hyundai EV lease California, electric crossover lease SoCal, Ioniq 5 lease deal, EV lease Los Angeles, Hyundai Ioniq 5 lease Southern California",
      h1: "Lease a Hyundai Ioniq 5 in Southern California",
      intro: "The Ioniq 5 is a fast-charging electric crossover that fits Southern California commutes and weekend range. We show you the real numbers before you commit, so the terms are yours to read, not theirs to hide.",
      bullets: ["Built for the SoCal EV driver who wants quick DC fast charging, a roomy crossover, and eligibility to check California EV incentives without guessing at the math.", "Every quote shows the all-in price, the money factor, and the drive-off amount in plain numbers, with no dealer markups added on top.", "Each listing carries a Hunter Score so you can compare leases on the same footing. An SSN is required; thin or new US credit is fine, we match you with lenders friendly to first-time borrowers and a co-signer can help."],
      cta: "Browse Ioniq 5 leases in our catalog",
    },
    ru: {
      title: "Лизинг Hyundai Ioniq 5 в Калифорнии | Hunter Lease",
      description: "Лизинг электрокроссовера Hyundai Ioniq 5 в Южной Калифорнии. Полная цена, money factor и платёж при выдаче видны сразу. Без дилерских наценок.",
      keywords: "Hyundai Ioniq 5 lease, Ioniq 5 lease Los Angeles, Hyundai EV lease California, electric crossover lease SoCal, Ioniq 5 lease deal, EV lease Los Angeles, Hyundai Ioniq 5 lease Southern California",
      h1: "Hyundai Ioniq 5 в лизинг в Южной Калифорнии",
      intro: "Ioniq 5 это электрокроссовер с быстрой зарядкой: хватает и на будни по Южной Калифорнии, и на выезды по выходным. Реальные цифры показываем до сделки, чтобы условия читали вы, а не прятал кто-то другой.",
      bullets: ["Водителю в SoCal, которому нужны быстрая DC-зарядка, просторный кроссовер и проверка льгот на электромобили в Калифорнии без догадок в расчётах.", "В каждом расчёте полная цена, money factor и сумма платежа при выдаче понятными числами. Дилерских наценок сверху нет.", "У каждого предложения есть Hunter Score, чтобы сравнивать лизинг на равных. SSN нужен обязательно. Короткая кредитная история в США это нормально: подбираем банки под первый кредит, а co-signer помогает."],
      cta: "Смотреть Ioniq 5 в каталоге",
    },
  },
  {
    slug: "hyundai-ioniq-6",
    filters: "make=Hyundai&model=Ioniq%206&sort=hunterScore",
    related: ["hyundai-elantra", "hyundai-sonata", "hyundai-tucson"],
    en: {
      title: "Hyundai Ioniq 6 Lease in SoCal | Hunter Lease",
      description: "Lease a Hyundai Ioniq 6 in Southern California with the all-in price, money factor, and drive-off shown up front. Hunter Score, zero dealer markups.",
      keywords: "Hyundai Ioniq 6 lease, Ioniq 6 lease Los Angeles, electric sedan lease California, EV lease Southern California, Ioniq 6 lease deal LA, Hyundai EV lease SoCal",
      h1: "Lease a Hyundai Ioniq 6 in Southern California",
      intro: "The Ioniq 6 is a sleek, long-range electric sedan built for SoCal commutes and road trips, and we put the full math on the table before you sign. Browse the live Ioniq 6 listings in our catalog and see exactly what each one costs.",
      bullets: ["Built for drivers who want a quiet, efficient EV daily with real freeway range, fast charging, and access to California HOV and EV perks, including first-time US borrowers with an SSN and thin or new credit.", "Every Ioniq 6 shows the all-in price, the money factor, and the full drive-off amount, with no hidden dealer markups baked into the lease.", "Each listing carries its Hunter Score so you can compare deals on the same terms and lease from a position of leverage, not guesswork."],
      cta: "See live Hyundai Ioniq 6 listings",
    },
    ru: {
      title: "Лизинг Hyundai Ioniq 6 в Калифорнии | Hunter Lease",
      description: "Лизинг Hyundai Ioniq 6 в Южной Калифорнии: цена «всё включено», money factor и платёж при выдаче видны сразу. Hunter Score, без наценок дилера.",
      keywords: "Hyundai Ioniq 6 lease, Ioniq 6 lease Los Angeles, electric sedan lease California, EV lease Southern California, Ioniq 6 lease deal LA, Hyundai EV lease SoCal",
      h1: "Лизинг Hyundai Ioniq 6 в Южной Калифорнии",
      intro: "Ioniq 6 это электроседан с большим запасом хода: для поездок по Калифорнии и на трассе. Всю математику показываем до того, как вы подпишете договор. Откройте каталог с актуальными Ioniq 6 и увидите точную стоимость каждого варианта.",
      bullets: ["Кому нужен тихий и экономичный электромобиль на каждый день: реальный запас хода на хайвее, быстрая зарядка, доступ к льготам Калифорнии для EV. В том числе тем, кто берёт машину в США впервые: нужен SSN, короткая или новая кредитная история это нормально.", "У каждого Ioniq 6 видны цена со всем включённым, money factor и полная сумма платежа при выдаче. Скрытых дилерских наценок в лизинге нет.", "У каждого объявления свой Hunter Score, чтобы сравнивать предложения на равных и брать машину с позиции силы, а не вслепую."],
      cta: "Смотреть актуальные Hyundai Ioniq 6",
    },
  },
];
