// Auto-assembled; Russian rewritten natively (russian-copy skill), em-dashes stripped.
export const NEWCOMER = {
  h1_en: "New here. Already ahead of the room.",
  h1_ru: "Вы недавно в США. А за столом у дилера уже сильнее всех.",
  sub_en: "Most buyers walk into a dealership with one number and no way to check it. You walk in with pre-negotiated lease and finance pricing, the exact credit tier your file lands in, a deal score that tells you if the offer is fair, and lenders that work with first-time US borrowers. An SSN is required. Thin or brand-new US credit is a normal starting point, not a problem to hide.",
  sub_ru: "Обычный покупатель приходит к дилеру с одной цифрой в голове и без всякой возможности её проверить. Вы приходите иначе: с готовыми ценами на лизинг и кредит, со своим кредитным tier и с оценкой, которая сразу покажет, честное это предложение или нет. И с банками, которые дают первый кредит в США. Нужен только SSN. Короткая кредитная история или её отсутствие это нормальный старт, а не повод прятаться.",
  trustline_en: "Soft credit check that does not affect your score. SSN required; thin or new US credit is welcome. A deal score on every offer and every fee named before you sign.",
  trustline_ru: "Мягкая проверка кредита, скор она не трогает. SSN обязателен, тонкий или новый скор в США мы приветствуем. На каждом предложении стоит оценка сделки, и все сборы названы до подписи.",
  cta_en: "See your tier and all-in price",
  cta_ru: "Узнать свой tier и полную цену",
  seo_title_en: "Car Leasing for Newcomers with an SSN and New Credit | hunter.lease SoCal",
  seo_title_ru: "Лизинг авто для новоприбывших с SSN | Hunter Lease",
  seo_desc_en: "New to the US with an SSN and thin credit? See your exact credit tier, lenders friendly to first-time borrowers, co-signer math, a deal score on every offer, and the full all-in lease and finance price. Bilingual Russian and English concierge across Southern California.",
  seo_desc_ru: "Недавно в США, есть SSN и тонкий скор? Узнайте свой credit tier, банки для первого заёмщика, расчёт с co-signer, оценку сделки на каждом предложении и полную цену lease и кредита. Консьерж говорит по-русски и по-английски по всей Южной Калифорнии.",
  keywords_en: "car lease for newcomers, lease with new credit, thin credit auto lease, first-time borrower car lease, SSN car lease California, co-signer lease, new to US car finance, lease deal score, building credit with a lease, Russian-speaking car concierge SoCal, transparent lease pricing Los Angeles",
  keywords_ru: "лизинг авто для новоприбывших, лизинг с новой кредитной историей, авто лизинг тонкая история, первый заёмщик лизинг авто, лизинг авто SSN Калифорния, лизинг с поручителем, финансирование авто для новичков в США, оценка сделки лизинг, кредитная история через лизинг, русскоязычный консьерж по авто, прозрачная цена лизинга Лос-Анджелес",
  bullets_en: ["You see the tier and the lender, not a vague 'you qualify': the exact credit tier your file maps to, the money factor tied to it, and which lenders we send it to", "An SSN is required; thin or new US credit is fine. We match you with lenders friendly to first-time borrowers, and a co-signer can open a stronger tier", "One all-in price, every line named: cap cost, money factor, fees, drive-off, and monthly. Every on-time payment reports to the bureaus and builds your file"],
  bullets_ru: ["Вы видите tier и банк, а не размытое «вы подходите»: точный credit tier по заявке, привязанный money factor и список банков, куда мы её отправляем.", "SSN нужен. Тонкий или новый скор в США не помеха: мы подбираем банки, которые дают первый заём, а co-signer открывает tier посильнее.", "Одна цена со всеми строками: cap cost, money factor, сборы, down и платёж в месяц. Каждый платёж в срок уходит в бюро и строит историю."],
  sections: [
    {
      title_en: "How the thin-credit lender match works",
      title_ru: "Как мы подбираем банк при тонком скоре",
      body_en: "You share your SSN for a soft credit check that does not affect your score. We read your file the way a dealer's finance desk does and show you the exact tier it lands in. Then we route it to lenders we already know work with first-time and newcomer borrowers, including the captive banks of specific brands and credit unions friendly to short US history, not just the one bank a single dealer happens to use. For each match you see the tier, the money factor tied to it, the term options, and the monthly payment that follows. Because the price is already set and transparent, the only question left is which lender gives you the best terms on it. You are comparing real offers instead of accepting the first one put in front of you.",
      body_ru: "Вы даёте SSN на мягкую проверку кредита, она не трогает скор. Мы читаем заявку так же, как финансовый отдел дилера, и сразу показываем tier, в который она попадает. Дальше отправляем её в банки, которые работают с первым заёмщиком и новоприбывшим: captive банки конкретных марок и credit unions, лояльные к короткой истории в США. Не один банк, с которым случайно работает дилер, а несколько. По каждому варианту вы видите tier, привязанный money factor, сроки и платёж в месяц. Цена уже зафиксирована и прозрачна, остаётся один вопрос: кто даст по ней лучшие условия. Вы сравниваете живые предложения, а не берёте первое.",
    },
    {
      title_en: "SSN required. Co-signer helps. History gets built.",
      title_ru: "SSN нужен. Co-signer помогает. История растёт.",
      body_en: "Here is the straight version, because that is the whole point. An SSN is required to apply. We do not do no-SSN or ITIN-only deals, and anyone who promises otherwise is not being honest with you. What you do not need is a long credit history. New and thin files are normal for newcomers, and the lenders we work with expect them. A co-signer with established US credit often opens a better tier and a lower money factor, and we put the with-and-without numbers in front of you so the trade-off is yours to weigh. Every approved lease reports to the bureaus, so the car you drive today is the credit history you use for the next one. No approval guarantees, no '99%' claims. You are not being rescued. You are setting up an asset you will use for years.",
      body_ru: "Скажем прямо, в этом весь смысл. Чтобы подать заявку, нужен SSN. Сделок без SSN или по одному ITIN мы не делаем, и кто обещает обратное, тот вас обманывает. А вот длинная кредитная история не нужна. Новый и тонкий скор у новичка это норма, и банки, с которыми мы работаем, к нему готовы. Co-signer с устоявшимся кредитом в США часто открывает tier повыше и money factor пониже. Мы кладём перед вами обе цифры, с ним и без, выбор за вами. Каждый одобренный lease уходит в бюро. Машина, на которой вы ездите сегодня, это история для следующей. Без гарантий одобрения, без обещаний «99%». Вас не спасают. Вы заводите актив, который работает на вас годами.",
    },
    {
      title_en: "Bilingual concierge, from first question to keys",
      title_ru: "Двуязычный консьерж от первого вопроса до ключей",
      body_en: "Every term, every line on the worksheet, and every document is available in Russian and English, so nothing important reaches you in a language you are still learning. A concierge who knows both the language and the SoCal market walks you through the tier, the lender choices, the deal score, and the all-in price, and answers in the language you think in. We tell you which documents a first-time borrower actually needs and why, so paperwork is not a wall. We handle the back-and-forth with the dealer and the lender. You make the call with the full picture in front of you and the quiet confidence of someone who knows exactly what they are signing.",
      body_ru: "Каждый термин, каждая строка в расчёте и каждый документ есть на русском и английском. Ничего важного не дойдёт до вас на языке, который вы ещё учите. Консьерж знает и язык, и рынок Южной Калифорнии. Он проведёт вас по tier, банкам, оценке сделки и полной цене и ответит на том языке, на котором вы думаете. Мы говорим, какие документы реально нужны первому заёмщику и зачем, чтобы бумаги не стали стеной. Переписку с дилером и банком берём на себя. Решаете вы, видя всю картину и точно зная, что подписываете.",
    },
  ],
};
